frankensteinWebUI/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from frankensteinWebUI import views
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newProject$', views.newProject, name='newProject'),
    url(r'^project$', views.project, name='project'),
    url(r'^emulate$', views.emulate, name='emulate'),


    url(r'^getProjectCfg$', views.getProjectCfg, name='getProjectCfg'),
    url(r'^projectSanityCheck$', views.projectSanityCheck, name='getProjectCfg'),

    url(r'^editConfig$', views.editConfig, name='editConfig'),
    url(r'^editGroup$', views.editGroup, name='editGroup'),
    url(r'^editSegment$', views.editSegment, name='editSegment'),
    url(r'^editSymbol$', views.editSymbol, name='editSymbol'),

    url(r'^loadELF$', views.loadELF, name='loadELF'),
    url(r'^loadIdb$', views.loadIdb, name='loadIdb'),
    url(r'^loadSegment$', views.loadSegment, name='loadSegment'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frankensteinWebUI/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.utils.http import urlencode
from django import forms

import os
import json
import glob
import hashlib
from binascii import hexlify, unhexlify
import traceback

from core.project import Project #TODO rename

#TODO move to forms.py
class projectNameForm(forms.Form):
    projectName = forms.CharField(max_length=100, help_text='Project Name', validators=[lambda x: not x])

class editConfigForm(forms.Form):
    projectName = forms.CharField(max_length=100, help_text='Project Name', validators=[lambda x: not x], widget=forms.HiddenInput())
    toolchain = forms.CharField(max_length=100, help_text='Toolchain', validators=[lambda x: not x])
    emulationCFlags = forms.CharField(max_length=1000, help_text='emulationCFlags', validators=[lambda x: not x])
    emulationCodeBase = forms.CharField(help_text="emulationCodeBase", validators=[lambda x: not int(x,16)])
    patchCFlags = forms.CharField(max_length=1000, help_text='patchCFlags', validators=[lambda x: not x])
    patchCodeBase = forms.CharField(help_text="patchCodeBase", validators=[lambda x: not int(x,16)])

class editGroupForm(forms.Form):
    projectName = forms.CharField(max_length=100, help_text='Project Name', validators=[lambda x: not x], widget=forms.HiddenInput())
    oldGroupName = forms.CharField(max_length=100, help_text='Old Group Name', validators=[lambda x: not x])
    newGroupName = forms.CharField(max_length=100, help_text='New Group Name', validators=[lambda x: not x])
    active = forms.BooleanField(help_text="Is Segment Active", required=False)

class editSegmentForm(forms.Form):
    projectName = forms.CharField(max_length=100, help_text='Project Name', validators=[lambda x: not x], widget=forms.HiddenInput())
    oldSegmentName = forms.CharField(max_length=100, help_text='Old Segment Name', validators=[lambda x: not x])
    oldGroupName = forms.CharField(max_length=100, help_text='Old Group Name', validators=[lambda x: not x])
    newSegmentName = forms.CharField(max_length=100, help_text='New Segment Name', validators=[lambda x: not x])
    newGroupName = forms.CharField(max_length=100, help_text='New Group Name', validators=[lambda x: not x])
    addr = forms.CharField(help_text="Segment Address", validators=[lambda x: not int(x,16)])
    active = forms.BooleanField(help_text="Is Segment Active", required=False)

class editSymbolForm(forms.Form):
    projectName = forms.CharField(max_length=100, help_text='Project Name', validators=[lambda x: not x], widget=forms.HiddenInput())
    oldSymbolName = forms.CharField(max_length=100, validators=[lambda x: not x], widget=forms.HiddenInput())
    oldGroupName = forms.CharField(max_length=100, validators=[lambda x: not x], widget=forms.HiddenInput())
    newSymbolName = forms.CharField(max_length=100, help_text='Symbol Name', validators=[lambda x: not x])
    newGroupName = forms.CharField(max_length=100, help_text='Group Name', validators=[lambda x: not x])
    value = forms.CharField(help_text="Value", validators=[lambda x: not int(x,16)])

class loadSegmentForm(forms.Form):
    projectName = forms.CharField(max_length=100, help_text='Project Name', validators=[lambda x: not x], widget=forms.HiddenInput())
    segment = forms.FileField(help_text='File', validators=[lambda x: not x])
    addr = forms.CharField(help_text="Segment Address", validators=[lambda x: not int(x,16)])
    groupName = forms.CharField(max_length=100, help_text='Segment Group', validators=[lambda x: not x])

class loadELFForm(forms.Form):
    projectName = forms.CharField(max_length=100, help_text='Project Name', validators=[lambda x: not x], widget=forms.HiddenInput())
    elf = forms.FileField(help_text='File', validators=[lambda x: not x])
    loadSymbols = forms.BooleanField(help_text="Load Symbols", required=False, initial=True)
    loadSegments = forms.BooleanField(help_text="Load Segments", required=False, initial=True)
    groupName = forms.CharField(max_length=100, help_text='Segment Group', validators=[lambda x: not x])

class loadIdbForm(forms.Form):
    projectName = forms.CharField(max_length=100, help_text='Project Name', validators=[lambda x: not x], widget=forms.HiddenInput())
    idb = forms.FileField(help_text='File', validators=[lambda x: not x])
    loadFunctions = forms.BooleanField(help_text="Load Functions", required=False, initial=True)
    loadSegments = forms.BooleanField(help_text="Load Segments", required=False, initial=True)


def render_wrapper(request, template, context={}):
    projects = glob.glob("projects/*/project.json")
    projects = map(lambda x: os.path.basename(os.path.dirname(x)), projects)

    context["projects"] = {}
    for projectName in projects:
        emulators = glob.glob(getProjectPath(projectName)+"/gen/*.exe")
        context["projects"][projectName] = map(os.path.basename, emulators)

    if "title" not in context:
        context["title"] = "Frankenstein"

    return render(request, template, context)

"""
Project Management
"""
def getProjectPath(projectName):
    return "projects/"+os.path.basename(projectName)

def getProjectByName(projectName):
    projectPath = "projects/"+os.path.basename(projectName)
    return Project(projectPath)

def index(request):
    return render_wrapper(request, 'index.html')

def project(request):
    projectName = request.GET["projectName"]
    if not os.path.isfile("projects/%s/project.json" % projectName):
        return redirect("/")

    project = getProjectByName(projectName)

    patches = glob.glob(getProjectPath(projectName)+"/gen/*.patch")
    patches = map(os.path.basename, patches)

    context = {
        "title": projectName,
        "projectName": projectName,
        "project": project,
        "patches": patches,
    }
    context['projectNameForm'] = projectNameForm({"projectName": projectName})
    context['editSegmentForm'] = editSegmentForm({"projectName": projectName})
    context['loadSegmentForm'] = loadSegmentForm({"projectName": projectName})
    context['loadELFForm'] = loadELFForm({"projectName": projectName})
    context['loadIdbForm'] = loadIdbForm({"projectName": projectName})

    return render_wrapper(request, 'project.html', context)


def newProject(request):
    if request.method == 'POST':
        form = projectNameForm(request.POST)
        if form.is_valid():
            project = getProjectByName(form.cleaned_data["projectName"])
            project.save()
            return redirect("/")
    else:
        form = projectNameForm()

    context = {}
    context['projectNameForm'] = form
    return render_wrapper(request, 'project/newProject.html', context)

def getProjectCfg(request):
    projectName = request.GET["projectName"]
    if not os.path.isfile("projects/%s/project.json" % projectName):
        redirect("/")

    project = getProjectByName(projectName)
    return HttpResponse(json.dumps(project.cfg))

def projectSanityCheck(request):
    projectName = request.GET["projectName"]
    if not os.path.isfile("projects/%s/project.json" % projectName):
        redirect("/")

    try:
        project = getProjectByName(projectName)
        project.sanity_check()
        return HttpResponse(project.error_msgs)
    except:
        return HttpResponse(traceback.format_exc())
    


"""
Config/Group/Segment/Symbol Management
"""

def editConfig(request):
    if request.method == 'POST':
        form = editConfigForm(request.POST)
        if form.is_valid():
            projectName = form.cleaned_data["projectName"]
            project = getProjectByName(projectName)
            succsess = True
            if not project.set_toolchain(form.cleaned_data["toolchain"]):
                succsess = False

            if not project.set_emulation_config(form.cleaned_data["emulationCFlags"], int(form.cleaned_data["emulationCodeBase"], 16)):
                succsess = False
            if not project.set_patch_config(form.cleaned_data["patchCFlags"], int(form.cleaned_data["patchCodeBase"], 16)):
                succsess = False

            if succsess:
                project.save()

            return HttpResponse(project.error_msgs)
    else:
        form = editConfigForm()

    return HttpResponse(str(form.errors))

def editGroup(request):
    if request.method == 'POST':
        form = editGroupForm(request.POST)
        if form.is_valid():
            projectName = form.cleaned_data["projectName"]
            oldGroupName = form.cleaned_data["oldGroupName"]
            newGroupName = form.cleaned_data["newGroupName"]
            active = form.cleaned_data["active"]

            project = getProjectByName(projectName)
            if "actionUpdate" in request.POST:
                project.group_update(oldGroupName, newGroupName)
                project.group_set_active(newGroupName, active)
                project.save()
            if "actionDelete" in request.POST:
                project.group_delete(oldGroupName)
                project.save()

            return HttpResponse(project.error_msgs)
    else:
        form = editGroupForm()

    return HttpResponse(str(form.errors))

def editSegment(request):
    if request.method == 'POST':
        form = editSegmentForm(request.POST)
        if form.is_valid():
            projectName = form.cleaned_data["projectName"]
            oldSegmentName = form.cleaned_data["oldSegmentName"]
            oldGroupName = form.cleaned_data["oldGroupName"]
            newSegmentName = form.cleaned_data["newSegmentName"]
            newGroupName = form.cleaned_data["newGroupName"]
            active = form.cleaned_data["active"]
            addr = int(form.cleaned_data["addr"], 16)

            project = getProjectByName(projectName)
            if "actionUpdate" in request.POST:

frankensteinWebUI/templates/base.html
<script src="/static/canvasjs.js"></script>
<link rel="stylesheet" href="/static/main.css" />
<link rel="stylesheet" href="/static/xterm.min.css" />
<script src="/static/xterm.min.js"></script>
<script src="/static/jquery-3.4.1.min.js"></script>

{% if title != "" %}
<title>{{ title }}</title>
{% endif %}


<script>
  //parse and filter json
  function convertActivityMap(map, start, stop, symbol_lookup) {
    var dataPoints = []
    var last_addr = start;
    dataPoints.push({x:start, y:0});
    for (var addr in map) {
      addr = parseInt(addr);

      if (addr < start || addr > stop) continue;

      if (last_addr + 4 < addr) {
        dataPoints.push({x:last_addr, y:0});
        dataPoints.push({x:addr, y:0});
      }

      //add point
      var point = {x:addr, y: Math.log2(map[addr])+1};
      if ((addr & 0xfffffffe) in symbol_lookup) {
        point.indexLabel = symbol_lookup[addr & 0xfffffffe];
        //point.indexLabelOrientation = "vertical";
        //point.indexLabelPlacement = "outside";
      }
      dataPoints.push(point);

      if (addr < last_addr) {alert(addr);alert(last_addr);}
      last_addr = addr;
    }
    dataPoints.push({x:last_addr, y:0});
    dataPoints.push({x:stop, y:0});

    return dataPoints;
  }


  function activityMap(container, title, exec_map, read_map, write_map, start, stop, symbol_lookup) {
    var exec = convertActivityMap(exec_map, start, stop, symbol_lookup);
    var read = convertActivityMap(read_map, start, stop, symbol_lookup);
    var write = convertActivityMap(write_map, start, stop, symbol_lookup);

    //add dom element
    var newDiv = document.createElement("div"); 
    newDiv.id = Math.random().toString(36).substring(2, 15);
    newDiv.style = "height: 300px; width: 100%;";
    var container = document.getElementById(container); 
    container.appendChild(newDiv);

    //draw chart
    var chart = new CanvasJS.Chart(newDiv.id,
    {
      backgroundColor: "#040404",

      zoomEnabled: true,
      title:{
        fontColor:"#d08000",
        text: title
      },
      axisX:{
        lineColor: "#d08000",
        tickColor: "#d08000",
        fontColor:"#d08000",
        titleFontColor:"#d08000",
        labelFontColor:"#d08000",

        labelFormatter: function (e) {
               return "0x" + e.value.toString(16);  
        }
       },
      axisY:{
        lineColor: "#d08000",
        tickColor: "#d08000",
        fontColor:"#d08000",
        titleFontColor:"#d08000",
        labelFontColor:"#d08000",

        labelFormatter: function (e) {
               return Math.floor(2**e.value);  
        }
      }, 
      toolTip:{
        backgroundColor: "#040404",
        fontColor:"#d08000",
        borderColor: "#d08000",
        cornerRadius: 0,
        borderThickness: 1,

        shared: true,
        contentFormatter: function (e) {
          var addr = e.entries[0].dataPoint.x
          if ((addr & 0xfffffffe) in symbol_lookup) {
            var name = symbol_lookup[addr & 0xfffffffe]
            return "0x"+addr.toString(16) + " ("+name+")";
          }

          return "0x"+addr.toString(16);
        }
      },
      legend: {
        fontColor:"#d08000"
        
      },
      data: [
        {type: "line", name: "Read", showInLegend: true, dataPoints: read, color: "#00d000"},
        {type: "line", name: "Write", showInLegend: true, dataPoints: write, color: "#d00000"},
        {type: "line", name: "Exec", showInLegend: true, dataPoints: exec, color: "#d000d0"},
      ]
    });

    chart.render();
  }


  function create_reverse_symbol_lookup(symbols) {
    var reverse = {}
    for (name in symbols) { 
      var addr = symbols[name];
      reverse[addr & 0xfffffffe] = name;
    }
    return reverse;
  }

  //Helper function to download files generated in js
  function download(filename, text) {
    var element = document.createElement('a');
    element.setAttribute('href', 'data:application/octet-stream;base64,' + btoa(text));
    element.setAttribute('download', filename);

    element.style.display = 'none';
    document.body.appendChild(element);

    element.click();

    document.body.removeChild(element);
  }


</script>


<div class="topnav">
  <h2> Frankenstein Build System </h2>
</div>


<div class="sidenav">
  {% for projectName, emulators in projects.items %}
    <a href="project?projectName={{ projectName }}">{{ projectName }} </a> <br>
    {% for emulatorName in emulators %}
      <a href="emulate?projectName={{ projectName }}&emulatorName={{ emulatorName }}">|--{{ emulatorName }}</a> <br>
    {% endfor %}
    <br>
  {% endfor %}
</div>


<div class="main">
  {% block content %}
  {% endblock %}
</div>




<script>
    var coll = document.getElementsByClassName("collapsible");
    for (var i = 0; i < coll.length; i++) {
      var content = coll[i].nextElementSibling;
      content.style.display = "none";

      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
          content.style.display = "none";
        } else {
          content.style.display = "block";
          if (typeof content.ondisplay != "undefined" && content.ondisplay != null)
            content.ondisplay();
        }
      });
    }
</script>

frankensteinWebUI/templates/emulate.html
{% extends 'base.html' %}
{% block content %}


<form action="emulate?projectName={{ projectName }}&emulatorName={{ emulatorName }}" method="POST">
  {% csrf_token %}

  <table style="width:100%">
    <tr><th>Stdin (Hex)</th><th>Tracepoints</th></tr>
    <tr>
      <td>
        <textarea id="stdin" name="stdin" rows="8" style="width:100%" onkeyup="update_stdin()"></textarea>
      </td><td>
        <textarea name="tracepoints" rows="8" style="width:100%">{{ emulateForm.cleaned_data.tracepoints }}</textarea>
      </td>
    </tr>
    <tr>
      <td colspan=2> <input type="submit" value="Run!" style="width:100%; height:40px; background:#001000"> </td>
    </tr>
  </table>

</form>

<script>
  function download_tracefile() {
    var tracefile = atob('{{ tracefile_b64 }}');
    download("testcase.trace", tracefile);
  }
</script>

<script>
  function update_stdin() {
    var stdin = document.getElementById('stdin').value;
    set_stdin(stdin);
  }

  function set_stdin(buffer) {
    var lines = [];

    buffer = buffer.replace(/[^0-9a-f\n]/gi,'');
    var splitted = buffer.split('\n');
    for (var b = 0; b < splitted.length; b += 1) {
      var block = splitted[b];

      chars = "";
      for (var i = 0; i < block.length; i += 2) {
        var hexchar = block.substr(i, 2);
        chars +=  block.substr(i, 2);
        if (hexchar.length == 2)
          chars += " ";
      }

      lines.push(chars);
    }
    lines = lines.join("\n").trimEnd();

    var selectionStart = document.getElementById("stdin").selectionStart;
    var selectionEnd = document.getElementById("stdin").selectionEnd;
    var offset = lines.length - document.getElementById("stdin").value.length;
    document.getElementById("stdin").value = lines;
    document.getElementById("stdin").selectionStart = selectionStart + offset;
    document.getElementById("stdin").selectionEnd = selectionEnd + offset;
  }

  set_stdin(`{{ emulateForm.cleaned_data.stdin }}`);
</script>


{% if success %}
  <br>
  <hr>
  <button onclick="download_tracefile()">Download Code Coverage</button> </br>
  <br>
{% endif %}

{% for t in emulator.results %}
    {% if t.stderr and t.stderr %}
        <div id="output_term_{{ t.resid }}" style="width:100%"></div>
        <script>
          var data = atob('{{ t.stderr }}').replace(/\n/g, '\r\n');
          var rows = data.split(/\r\n|\r|\n/).length;
          var term = new Terminal();
          term.open(document.getElementById('output_term_{{ t.resid }}'));
          term.resize(120, Math.min(40, rows+1));
          term.setOption('fontSize', 12);
          term.write(data);

          //disable scrollbar
          var viewports = term.element.getElementsByClassName("xterm-viewport");
          for (var i in viewports)
            viewports[i].style.overflow = "auto"
        </script>
    {% endif %}

</br>
  <h3> {{ t.pc_symbolized }} - {{ t.instr }} - {{ t.reason }}</h3>
</br>
    <!-- registers -->
    <table style="width:100%">
      <tr>
        <td style="width:12.5%">r0=0x{{ t.regs.r0 | stringformat:'x' }}</td>
        <td style="width:12.5%">r1=0x{{ t.regs.r1 | stringformat:'x' }}</td>
        <td style="width:12.5%">r2=0x{{ t.regs.r2 | stringformat:'x' }}</td>
        <td style="width:12.5%">r3=0x{{ t.regs.r3 | stringformat:'x' }}</td>
        <td style="width:12.5%">r4=0x{{ t.regs.r4 | stringformat:'x' }}</td>
        <td style="width:12.5%">r5=0x{{ t.regs.r5 | stringformat:'x' }}</td>
        <td style="width:12.5%">r6=0x{{ t.regs.r6 | stringformat:'x' }}</td>
        <td style="width:12.5%">r7=0x{{ t.regs.r7 | stringformat:'x' }}</td>
      </tr><tr>
        <td>r8=0x{{ t.regs.r8 | stringformat:'x' }}</td>
        <td>r9=0x{{ t.regs.r9 | stringformat:'x' }}</td>
        <td>r10=0x{{ t.regs.r10 | stringformat:'x' }}</td>
        <td>r11=0x{{ t.regs.r11 | stringformat:'x' }}</td>
        <td>r12=0x{{ t.regs.r12 | stringformat:'x' }}</td>
        <td>sp=0x{{ t.regs.sp | stringformat:'x' }}</td>
        <td>lr=0x{{ t.regs.lr | stringformat:'x' }}</td>
        <td>pc=0x{{ t.regs.pc | stringformat:'x' }}</td>
      </tr>
    </table>
  </br>


  <button type="button" class="collapsible">Show Memory Diff</button>
  <div class="collapsibleContent" id="memdiff_term_{{ t.resid }}" style="width:100%"></div>

  <script>
    var memdiff_rendered_{{ t.resid }} = false;

    function mediff_render_{{ t.resid }}() {
      if( memdiff_rendered_{{ t.resid }} == false) {
        memdiff_rendered_{{ t.resid }} = true;

        var text = atob('{{ t.memdif_rendered }}').replace(/\n/g, '\r\n');
        var rows = text.split(/\r\n|\r|\n/).length;
        var term = new Terminal();
        term.resize(120, Math.max(rows, 1));
        term.setOption('fontSize', 12);
        term.open(document.getElementById('memdiff_term_{{ t.resid }}'));
        term.write(text);

        //disable scrollbar
        var viewports = term.element.getElementsByClassName("xterm-viewport");
        for (var i in viewports)
          viewports[i].style.overflow = "hidden";
      }

    }

    var memdiff = document.getElementById("memdiff_term_{{ t.resid }}");
    memdiff.ondisplay = mediff_render_{{ t.resid }};
  </script>

  <p></p>

{% endfor %}

{% if success %}
  <h3>Activity:</h3> </br>
  <div id="ActivityContainer" style="width: 100%;"> </div>
{% endif %}


<script>
  var coverage_activity = {{ emulator.coverage_activity_json|safe }};
  var read_activity = {{ emulator.read_activity_json|safe }};
  var write_activity = {{ emulator.write_activity_json|safe }};
  var symbol_table  = create_reverse_symbol_lookup( {{ symbols_json|safe }} );

  {% for name, addr, size in emulator.segments %}
      activityMap("ActivityContainer", "{{ name }}", coverage_activity, read_activity, write_activity, {{ addr }}, {{ addr | add:size }}, symbol_table);
  {% endfor %}
</script>



{% endblock %}

frankensteinWebUI/templates/index.html
{% extends 'base.html' %}
{% block content %}

Create Project

<form action="newProject" method="POST">
  {% csrf_token %}
  <input type="text" name="projectName" maxlength="100" required id="id_projectName">
  <input type="submit" value="Create">
</form>

{% endblock %}